Profile module
Brod8362/csoc4353 pull request #10
Opened 2024-03-23 03:25 UTC by bbqcandy

# Update Profile function and tests created
* created *update_profile* function in *database.rs*
* created tests for *update_profile* 
* added tables for the necessary information to be added by the function

2024-03-23 17:15 UTC, Brod8362 requested changes
Overall good, needs some minor changes.

Database functionality is not important for the scope of assignment 3 but I'm happy to accept it if the requested changes are made.

2024-03-23 17:15 UTC, Brod8362 commented on src/backend/src/database.rs
> +            password_salt BLOB NOT NULL,
This should all live in a separate table with a foreign key that references user_id. This table here is specifically for auth and auth only.

2024-03-23 17:15 UTC, Brod8362 commented on src/backend/src/database.rs
> +pub async fn update_profile(pool: &Pool<Sqlite>, user_id: &str, full_name: Option<&str>, address1: Option<&str>, city1: Option<&str>, state1: Option<&str>, zip1: Option<&str>, address2: Option<&str>,
Everything here should be non-Optional, and handled in the function(s) that call this function.
Let the frontend (as in, the routes) deal with missing info - let the backend (this function) deal with validation.

Make sure we consider the length restrictions imposed by the assignment for each field.

A lot of the functionality done manually here can be automatically imposed by using `Option<T>` in the form itself. Then, rocket will automatically return a 422 when fields are missing. 

With missing fields handled implicitly by rocket, all we need to do is length validation, which is OK to happen inside of this function.

2024-03-23 17:15 UTC, Brod8362 commented on src/backend/src/database.rs
> +        let update_profile_res = crate::database::update_profile(&pool, full_name, address1, city1, state1, zip1, address2, city2, state2, zip2).await;
This is good, but alongside validating that the result is OK, we need to query the data and make sure its exactly what we expect.

This test will probably slim down a lot once the changes regarding Optional fields (as ref'd in a different comment)

2024-03-23 17:15 UTC, Brod8362 commented on src/backend/src/main.rs
> +                routes::submit_quote
:+1:

2024-03-23 17:15 UTC, Brod8362 commented on src/backend/src/routes.rs
> +
This is not related to this PR so I will not be providing feedback on the quotes

Really, it shouldn't even be here, but it's not a big deal

2024-03-23 17:15 UTC, Brod8362 commented on src/backend/static/styles.css
> +    --orange: #ce812c;
I like the fun names

2024-03-23 17:15 UTC, Brod8362 commented on src/backend/templates/fuel_quote_history.html.tera
> +        <button hx-get="/page/quote_history" hx-swap="innerHTML" hx-target="#display-box" hx-select="#tab2">Quote 2</button>
Having a bunch of tabs is not how we will approach this problem in execution.

This is also outside the scope of this PR so I will not be leaving much in terms of review. This has more to do with #11

2024-03-23 17:15 UTC, Brod8362 commented on src/backend/templates/login_page.html.tera
> +    <style>
Most of this is just formatting changes so not much to say.
I don't agree with the main block being called `#content-form` - it is not a form. It is the main content of the page.

Let's make sure that class names etc accurately represent their purpose.

2024-03-26 16:50 UTC, bbqcandy commented on src/backend/src/database.rs
> +pub async fn update_profile(pool: &Pool<Sqlite>, user_id: &str, full_name: Option<&str>, address1: Option<&str>, city1: Option<&str>, state1: Option<&str>, zip1: Option<&str>, address2: Option<&str>,
so just to be clear, everything here should not have `Option<T>` and I should put that in the form in 'routes.rs' handle it instead? i.e. the declaration will just be:
`pub async fn update_profile(pool: &Pool<Sqlite>, user_id: &str, full_name: &str, address1: &str, city1: &str, state1: &str, zip1: &str, address2: &str, city2: &str, state2: &str, zip2: &str) -> Result<(), Box<dyn Error>> {`

as for the length restriction, why is that handled here and not by rocket?

2024-03-26 18:30 UTC, Brod8362 commented on src/backend/src/database.rs
> +pub async fn update_profile(pool: &Pool<Sqlite>, user_id: &str, full_name: Option<&str>, address1: Option<&str>, city1: Option<&str>, state1: Option<&str>, zip1: Option<&str>, address2: Option<&str>,
Something I missed the first time around -

There should not be city2, state2, etc. There's address 1 (e.g address line 1) and address 2 (address line 2)

The complete list of fields should be:

- full_name
- address_1
- address_2 (optional)
- city
- state
- zipcode

> as for the length restriction, why is that handled here and not by rocket?
Rocket does not have the ability to enforce specific lengths that I know of. But, because in the struct that represents the form, only `address_2` is optional, Rocket will automatically reject requests that are missing required fields with a `422`. Of course, that still needs to be unit tested.

Remember that the length restrictions set on the client are not the be-all end-all and we still need to validate it again on the server side.

2024-03-26 19:12 UTC, bbqcandy commented on src/backend/src/database.rs
> +pub async fn update_profile(pool: &Pool<Sqlite>, user_id: &str, full_name: Option<&str>, address1: Option<&str>, city1: Option<&str>, state1: Option<&str>, zip1: Option<&str>, address2: Option<&str>,
>The complete list of fields should be:
>* full_name
>* address_1
>* address_2(optional)
>* city
>* state
>* zipcode

If that's the case, then we need to change all the other related parts bc I was basing it off them. Idk why but ig I figured address 2 would include city state and zip sepratley.

2024-03-26 19:13 UTC, Brod8362 commented on src/backend/src/database.rs
> +pub async fn update_profile(pool: &Pool<Sqlite>, user_id: &str, full_name: Option<&str>, address1: Option<&str>, city1: Option<&str>, state1: Option<&str>, zip1: Option<&str>, address2: Option<&str>,
That's fine, for now just change the profile page - the rest comes later

2024-03-27 01:32 UTC, closed without merging