Provide password restriction on register page
Brod8362/csoc4353 pull request #105
Opened 2024-04-26 19:35 UTC by Mnguyener

![image](https://github.com/Brod8362/csoc4353/assets/52382029/91694ff7-ff0e-49b8-a444-7b67ba000d13)
Closes #104

2024-04-26 22:52 UTC, tnttruong commented
I agree, I think it should just be white text like the "Please login or register" and be placed right underneath the password field

2024-04-27 00:07 UTC, Brod8362 requested changes
Message should be on the registration page, not the login page

2024-04-27 00:31 UTC, Mnguyener commented
I've rebased to update my branch and made the changes needed.

![image](https://github.com/Brod8362/csoc4353/assets/52382029/4b4dc34e-924d-4004-92c4-2dba32146f56)

2024-04-27 00:49 UTC, Brod8362 approved these changes

2024-04-27 00:53 UTC, merged