Remove address2 on the fuel quote form
Brod8362/csoc4353 pull request #50
Opened 2024-04-04 03:38 UTC by Mnguyener

This PR address issue #39 by removing the option to select an address and only display one address.
![image](https://github.com/Brod8362/csoc4353/assets/52382029/5349bac7-bda1-4213-be0c-960af40614be)

The current format isn't great but it does the job as of now.

2024-04-04 04:46 UTC, Brod8362 commented
Does this handle pulling the address from the user's profile?
Since the user isn't specifying the address, we need to pull it in from their profile.

Additionally, since profiles are now implemented, can you have it show the profile data pulled from the database?

(This means we also need to handle the case where a user's profile isn't set yet, and in that case we should force them into setting their profile data first)

2024-04-05 21:30 UTC, Mnguyener commented
It does not handle pulling the address. Good catch, I'm going to work on that.

I will also work on showing the profile data pulled from the database.

2024-04-09 18:21 UTC, Brod8362 commented
What's the status on this, is it ready for re-review?

2024-04-10 20:29 UTC, Mnguyener commented
No, I still need to pull the address from the ProfileData struct

2024-04-15 23:17 UTC, tnttruong commented
Whenever I add in 2 addresses, it'll show both of them on the same line in the form
![image](https://github.com/Brod8362/csoc4353/assets/33504642/17a00797-2fdb-4d8a-8fa6-de37a5e2e42f)

2024-04-15 23:28 UTC, Mnguyener commented
Good point, I forgot to separate the address 1 from address 2. I'll fix that ASAP

2024-04-16 00:29 UTC, Mnguyener commented
Here's what the addresses look like now:

### Fuel Quote Form
![image](https://github.com/Brod8362/csoc4353/assets/52382029/60201fd5-e112-44a6-a918-a7e8027cdb7a)

### Quote #
![image](https://github.com/Brod8362/csoc4353/assets/52382029/e681ddc5-366b-4fd1-aa1d-ff3c9a9aac6f)

2024-04-16 03:57 UTC, Brod8362 requested changes
See comments

2024-04-16 03:57 UTC, Brod8362 commented on src/backend/src/database.rs
> +        profile.address1 + " " + &addr2 + " " + &profile.city + ", " + &profile.state + ", " + &profile.zip
Use string interpolation (`format!()`), not concatenation

2024-04-16 03:57 UTC, Brod8362 commented on src/backend/src/database.rs
> +        profile.address1 + " " + &profile.city + ", " + &profile.state + ", " + &profile.zip
Same as above

2024-04-16 03:57 UTC, Brod8362 commented on src/backend/src/database.rs
> +        let addr_long = "Bunker address 2 Copied City, Japan, 11001";
There should be a comma between address 1 and 2

2024-04-16 03:57 UTC, Brod8362 commented on src/backend/src/routes.rs
> +                    address2: profile.address2, //TODO: account for if addr2 doesn't exist
.Make sure this TODO is handled in this PR. If it already is, then remove this comment

2024-04-16 03:57 UTC, Brod8362 commented on src/backend/src/routes.rs
> +        let client = Client::tracked(rocket().await).await.expect("valid rocket instance");
Incorrect, use the `test_client` function (see other unit tests for examples)

2024-04-16 04:00 UTC, Mnguyener commented on src/backend/src/routes.rs
> +                    address2: profile.address2, //TODO: account for if addr2 doesn't exist
The reason why I didn't handle this yet is because I thought that the `address2` is not made optional yet due to this piece of code
``` let address2 = match &form.address2 {
        Some(a) => a.clone(),
        None => "".to_string()
    };```

2024-04-16 17:06 UTC, Mnguyener commented on src/backend/src/routes.rs
> +        let client = Client::tracked(rocket().await).await.expect("valid rocket instance");
Got it, it wasn't shown previously because I hadn't rebased yet

2024-04-16 20:16 UTC, Mnguyener commented
Waiting on #58

2024-04-16 20:32 UTC, Brod8362 requested changes

2024-04-16 20:32 UTC, Brod8362 commented on src/backend/src/database.rs
> +        format!("{}, {} {}, {}, {}", profile.address1, &addr2, &profile.city, &profile.state, &profile.zip)
Missing comma here between address 1 and 2

2024-04-16 20:32 UTC, Brod8362 commented on src/backend/src/database.rs
> +        format!("{} {}, {}, {}", profile.address1, &profile.city, &profile.state, &profile.zip)
Missing comma here between address 1 and 2

2024-04-16 20:32 UTC, Brod8362 commented on src/backend/templates/fuel_quote_form.html.tera
> +                <p>{{address1}}, {% if address2 %}<br>{{ address2 }}{% endif %}<br>{{city}}, {{state}}, {{zip}}</p>
Could just generate this on the backend but this is fine

2024-04-16 20:54 UTC, tnttruong approved these changes
Formatting looks good now!

2024-04-18 13:38 UTC, Brod8362 requested changes
Still a comma missing but otherwise looks good

2024-04-18 13:38 UTC, Brod8362 commented on src/backend/src/database.rs
> +        format!("{} {}, {}, {}", profile.address1, &profile.city, &profile.state, &profile.zip)
Comma still missing here

2024-04-19 22:50 UTC, Mnguyener commented on src/backend/src/database.rs
> +        format!("{} {}, {}, {}", profile.address1, &profile.city, &profile.state, &profile.zip)
Oops, that got lost in the history of commits. Remedying it right now

2024-04-19 23:43 UTC, Mnguyener commented
Just rebased from main. Please review again! Hopefully this will be the last

2024-04-20 13:51 UTC, Brod8362 approved these changes
Looks good

2024-04-20 19:01 UTC, tnttruong commented
Works great for me

2024-04-20 19:01 UTC, tnttruong approved these changes

2024-04-20 19:02 UTC, merged