address2 issues fixed
Brod8362/csoc4353 pull request #64
Opened 2024-04-16 22:12 UTC by bbqcandy

Fixed the issues with address2 in `database.rs` and `routes.rs`
tests all should pass as well

2024-04-18 13:40 UTC, Brod8362 requested changes
See comments

2024-04-18 13:40 UTC, Brod8362 commented on src/backend/src/database.rs
> +        assert_eq!(profile.address2.as_ref().unwrap_or(&String::new()), address2.as_ref().unwrap_or(&String::new()));
I think there's a better way to do this, this seems very excessive.
Should be as easy as `assert_eq!(address2, profile.address2)`

2024-04-18 13:40 UTC, Brod8362 commented on src/backend/src/database.rs
> +        assert_eq!(profile.address2.as_ref().unwrap_or(&String::new()), address2.as_ref().unwrap_or(&String::new()));
There should be a better way (see other comment)

2024-04-18 13:40 UTC, Brod8362 commented on src/backend/src/routes.rs
>      let address2 = match &form.address2 {
This shouldn't be needed anymore at all, can just pass it through directly from the form struct

2024-04-21 19:46 UTC, bbqcandy commented
just made the changes requested

2024-04-21 20:59 UTC, Mnguyener approved these changes
Looks good

2024-04-21 21:41 UTC, Brod8362 requested changes
See single comment, otherwise good

2024-04-21 21:59 UTC, Brod8362 commented
Also, please have more descriptive commit messages that aren't just "fixed this" or "made changes"

2024-04-22 03:37 UTC, merged